# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: BackendSecrets

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Secret Substition
      uses: microsoft/variable-substitution@v1
      with:
          files: 'FootballCrimes.API/appsettings.json'
      env:
          ConnectionStrings.DefaultConnection: ${{secrets.CONNECTION_STRING}}
          ApiKeys.FootballData: ${{ secrets.API_KEY }}

    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Test with dotnet
      run: dotnet test

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: and-tech-server
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CFA3FA39B5824B16BEF553BBE5D28CA7 }}
        package: ${{env.DOTNET_ROOT}}/myapp

